### ISSUE TITLE
hallo ini yg saya integrasikan

### ISSUE THREAD

**Issue by adamramadhan** [rizdaprasetya/snap-whmcs#2]
Exception: Veritrans Error (): in /home/xxx/public_html/modules/gateways/veritrans-lib/Veritrans/ApiRequestor.php:96
Stack trace:
#0 /home/xxx/public_html/modules/gateways/veritrans-lib/Veritrans/ApiRequestor.php(17): Veritrans_ApiRequestor::remoteCall('https://api.mid...', 'Mid-server-rZNa...', false, false)
#1 /home/xxx/public_html/modules/gateways/veritrans-lib/Veritrans/Transaction.php(17): Veritrans_ApiRequestor::get('https://api.mid...', 'Mid-server-rZNa...', false)
#2 /home/xxx/public_html/modules/gateways/veritrans-lib/Veritrans/Notification.php(20): Veritrans_Transaction::status(NULL)
#3 /home/xxx/public_html/modules/gateways/callback/veritrans.php(45): Veritrans_Notification->__construct()
#4 {main}

knp ya?

**Comment by adamramadhan** [comment]
apakah bisa mampir ke tempat mas bro untuk menyelesaikan integrasi whmcsnya?

**Comment by rizdaprasetya** [comment]
@adamramadhan Ini apakah terjadi ketika klik **Send Test Notification** dari Dashboard?
Jika iya, maka memang expected. Karena Dashboard hanya mengirim notification dummy untuk ping URL notificationnya, yang tidak bisa dihandle oleh WHMCS. Kalau mau test notification, silahkan langsung buat order saja dari WHMCS dengan payment Midtrans. Nanti akan dapat notification.

Silahkan kontak email support[at]midtrans.com jika memang perlu meeting.
